services:
    db:
        container_name: postgres
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DATABASE=${POSTGRES_DATABASE}
        ports:
            - 5433:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - teastream-backend

    redis:
        container_name: redis
        image: redis:latest
        restart: always
        ports:
            - 6379:6379
        networks:
            - teastream-backend
        command: redis-server --requirepass ${REDIS_PASSWORD}
        volumes:
            - redis_data:/data

volumes:
    postgres_data:
    redis_data:
networks:
    teastream-backend:
